Repository Gillian59/game-ecommerce, pull requests merged in 2020-10, with the labels that each got.

#31 add packages authorization
  README.md
  package.json
  yarn.lock
Labels: Back, LOGIN

#30 changed the home banner display
  public/images/retro-bg.jpg
  public/styles/main.css
  src/controllers/games.controller.ts
  views/components/banner.njk
  views/layout/index.njk
  views/pages/home.njk
Labels: Accueil, Front

#34 Footer
  README.md
  public/images/logo.png
  public/styles/main.css
  views/layout/footer.njk
  views/layout/index.njk
  views/pages/home.njk
Labels: Accueil, Front

#35 création formulaire inscription
  public/styles/sign-up.css
  src/server.ts
  views/pages/sign-up.njk
Labels: Front, SIGN

#37 creation-page-panier
  public/styles/checkout.css
  public/styles/panier.css
  src/server.ts
  views/layout/index.njk
  views/layout/navbar.njk
  views/pages/checkout.njk
  views/pages/login.njk
  views/pages/panier.njk
  views/pages/sign-up.njk
Labels: Checkout, Front, Panier

#39 Connect backend
  src/index.ts
  src/server.ts
  views/layout/navbar.njk
Labels: Back, LOGIN

#42 changed the server logic to a sc usage of login
  src/controllers/games.controller.ts
  src/server.ts
Labels: Accueil, Back, Front

#44 Test end to end + ajout de CSS sur les platforms
  package.json
  public/styles/games.css
  public/styles/platforms.css
  src/test/e2e.test.ts
  views/games/index.njk
  views/platforms/index.njk
  views/platforms/show.njk
  yarn.lock
Labels: Front
